version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-example-1gmnkwh7qi4h4"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sajm4grpmnx8"
s3_prefix = "aws-sam-example-1gmnkwh7qi4h4"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"